name: Build Ubuntu lastest

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install wxWidgets
        run: |
          sudo apt update
          sudo apt install libwxgtk3.2-dev

      - name: Configure
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release
        env:
          CXX: g++-14

      - name: Build
        run: cmake --build build -j$(nproc --all)

      - uses: actions/upload-artifact@v4
        with:
          name: CeDImu-ubuntu-x86_64
          path: build/CeDImu
