name: Build Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3.1.0

      - name: Cache vcpkg
        id: cache-vcpkg
        uses: actions/cache@v3
        with:
          path: C:/vcpkg
          key: ${{ runner.os }}-vcpkg

      - name: Install wxWidgets
        if: steps.cache-vcpkg.outputs.cache-hit != 'true'
        run: vcpkg install wxwidgets:x64-windows-static

      - name: Configure
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DCMAKE_CONFIGURATION_TYPES=Release -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: cmake --build build --config Release

      - name: Upload build
        uses: actions/upload-artifact@v3.1.0
        with:
          name: CeDImu-windows-x86_64
          path: ./build/Release/CeDImu.exe
