name: Build Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          ref: actions-test

      - name: Install wxWidgets
        run: vcpkg install wxwidgets:x64-windows-static

      - name: Generate Makefile
        run: cmake . -B build -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -DVCPKG_TARGET_TRIPLET=x64-windows-static -DVCPKG_BUILD_TYPE=release

      - name: Build
        run: cmake --build build

      - name: Upload build
        uses: actions/upload-artifact@v3.1.0
        with:
          name: CeDImu-windows-x86_64.exe
          path: .\build\CeDImu.exe
