name: Build macOS (x86_64)

on: [push, pull_request]

jobs:
  build-x86_64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install dependencies
        run: brew install wxwidgets@3.2 dylibbundler create-dmg llvm

      - name: Generate Makefile
        run: CXX=$(brew --prefix llvm)/bin/clang++ cmake . -DCMAKE_BUILD_TYPE=Release -DCEDIMU_ENABLE_LTO=OFF

      - name: Build
        run: make -j$(sysctl -n hw.physicalcpu)

      - name: Prepare application bundle
        run: |
             mkdir -p ./CeDImu.app/Contents/{MacOS,libs,Resources}
             cp ./resources/Info.plist ./CeDImu.app/Contents/
             cp ./resources/CeDImu-v3.icns ./CeDImu.app/Contents/Resources/

      - name: Copy binary to bundle and bundle dependency dylibs
        run: |
             cp ./CeDImu ./CeDImu.app/Contents/MacOS/
             dylibbundler -od -b -x ./CeDImu.app/Contents/MacOS/CeDImu -d ./CeDImu.app/Contents/libs/

      - name: Create dmg installer
        run: create-dmg --volname "CeDImu Installer" --volicon "resources/CeDImu-v3.icns" --hide-extension "CeDImu.app" --window-pos 200 120 --window-size 800 400 --icon-size 100 --app-drop-link 600 185 "CeDImu-Installer.dmg" "./CeDImu.app/"

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: CeDImu-Installer-x86_64.dmg
          path: ./CeDImu-Installer.dmg

      - name: Run tests
        run: ./tests/tests
