name: Build Windows

on: [push]

jobs:
  test-job:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - run: vcpkg update

      - name: Install wxWidgets
        run: vcpkg install wxwidgets:x64-mingw-static

      - name: Generate Makefile
        run: cmake . -G "MinGW Makefiles" -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-mingw-static -Wno-dev

      - name: Build
        run: mingw32-make

      - name: Upload build
        uses: actions/upload-artifact@v3.1.0
        with:
          name: CeDImu.exe
          path: .\CeDImu.exe
