name: Build Windows MinGW

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          ref: actions-test

      - name: Install wxWidgets
        run: vcpkg install wxwidgets:x64-mingw-static

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: logs.txt
          path: C:\vcpkg\buildtrees\wxwidgets\install-x64-mingw-static-dbg-out.log

      - name: Generate Makefile
        run: cmake -B build -S . -G "MinGW Makefiles" -DCEDIMU_ENABLE_LTO=0 -DCMAKE_BUILD_TYPE=Release -DVCPKG_TARGET_TRIPLET=x64-mingw-static -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake -Wno-dev

      - name: Build
        run: cmake --build build --config Release

      - name: Upload build
        uses: actions/upload-artifact@v3.1.0
        with:
          name: CeDImu-windows-x86_64.exe
          path: ./build/Release/CeDImu.exe
