name: Build Windows

on: [push]

jobs:
  test-job:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
            platform: x64

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Install vcpkg
        uses: actions/checkout@v3
        with:
          repository: Microsoft/vcpkg
          path: vcpkg
      - run: dir vcpkg
      - run: .\vcpkg\bootstrap-vcpkg.bat

      - name: Install wxWidgets
        run: .\vcpkg\vcpkg.exe install wxwidgets

      - name: Generate Makefile
        run: cmake . -DCMAKE_TOOLCHAIN_FILE=[path to vcpkg]/scripts/buildsystems/vcpkg.cmake

      - name: Build
      - run: mingw32-make
