name: Build Linux
on: [push]
jobs:
    test-job:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: echo "checked out"
            - run: sudo apt install libwxgtk3.0-dev
            - run: mkdir build && cd build
            - run: cmake .. -DENABLE_LOG=1
            - run: make

